name: Build C++ Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up caching for build artifacts
        uses: actions/cache@v4
        with:
          path: build_cache
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.cpp') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Create build directory
        run: mkdir -p build_cache

      - name: Compile C++ files on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          find . -name '*.cpp' | while read file; do
            output="build_cache/$(basename ${file%.cpp})-${RUNNER_OS}.out"
            # Only compile if output file doesn't exist or source file is newer
            if [[ ! -f "$output" || "$file" -nt "$output" ]]; then
              g++ -o "$output" "$file"
            fi
          done

      - name: Compile C++ files on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.cpp | ForEach-Object {
            $output = "build_cache/$($_.BaseName)-windows.exe"
            # Only compile if output file doesn't exist or source file is newer
            if (!(Test-Path $output) -or ($_.LastWriteTime -gt (Get-Item $output).LastWriteTime)) {
              g++ $_.FullName -o $output
            }
          }

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries-${{ matrix.os }}
          path: build_cache/
