name: Build C++ Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile C++ files on Linux/macOS
        if: runner.os != 'Windows'
        run: |
          find . -name '*.cpp' -exec sh -c 'g++ -o "${1%.cpp}-${RUNNER_OS}.out" "$1"' _ {} \;

      - name: Compile C++ files on Windows
        if: runner.os == 'Windows'
        run: |
          Get-ChildItem -Recurse -Filter *.cpp | ForEach-Object { g++ $_.FullName -o "$($_.BaseName)-windows.exe" }

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-binaries-${{ matrix.os }}
          path: |
            **/*.exe
            **/*.out
